name: Build

on:
  push:
    branches: [feat/support-latest-spec]
    paths:
      - '.github/workflows/ci.yml'
      - 'plugins/**'
      - 'src/**'
      - 'test/**'
      - '.browserslistrc'
      - '.prettierrc'
      - 'karma.conf.cjs'
      - 'package.json'
      - 'package-lock.json'
      - 'rollup.config.js'
      - 'tsconfig.json'

jobs:
  build:
    name: 'Build'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [18.x]
        os: [windows-2019, macOS-11]

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Lint & Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
        env:
          CI: true
