name: Build

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'plugins/**'
      - 'src/**'
      - 'test/**'
      - '.browserslistrc'
      - '.prettierrc'
      - 'karma.conf.cjs'
      - 'package.json'
      - 'package-lock.json'
      - 'rollup.config.js'
      - 'tsconfig.json'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use NodeJS 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install
        run: npm ci
      - name: Lint & Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dist
          path: dist
          
